### PR TITLE
adding muon test files

### PR DESCRIPTION
**Pull request by AMWMitchell**
Adding muon test files for MST flashcam and sst-1m to ctapipe resources

### CODE REVIEW

**Comment by kosack** [comment]
Do we need both of these? It would add 80 MB to the size of ctapipe-extras, which is already quite large (and close to exceeding the package limits on anaconda).  Could we have smaller versions perhaps?

**Comment by AMWMitchell** [comment]
One is probably fine (would suggest mst). 
At some point it would be good to be able to share sets of muon simulation files (3x tel, 3x opt_eff minimum), but via github might not be the best place for this.

**Comment by kosack** [comment]
Ok, could you remove one of them and re-push? Preferably keep the smallest one, since we are already close to exceeding size limits.  I'll probably remove the test gamma files soon and replace them with better/smaller ones as well once we have a nice final-array-layout version (prod4 or whatever).

**Comment by kosack** [comment]
see https://github.com/cta-observatory/ctapipe/issues/1073

**Comment by maxnoe** [comment]
I think this is solved by adding #29

**Comment by AMWMitchell** [comment]
Not so sure, #29 seems to be for LST only. 
This issue in general is better covered by the remote data option @kosack mentions above. 
(https://github.com/cta-observatory/ctapipe/issues/1073)
Edit: I think it is correct to close / merge this issue; less certain it is solved.

**Comment by maxnoe** [comment]
@AMWMitchell Yes, I agree. We need muon test data for all telescopes, especially the SST as the current code is in ctapipe is not able to handle dual-mirror telescopes.

But for now, I think it's not important which single mirror telescope is included here for simple tests.

**Pull request closed without merging**
