### PR TITLE
Rename LST to differentiate between real and simulated

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by rlopezcoto** [comment]
This will be very useful, at the moment we are always struggling with the camera version when reading simulations.

Regarding the geometry for real data, now we are at version `-004` and I do not expect any changes, but would there be a way of defining `LSTCamReal` that links to the latest geometry version? Like that any change would be transparent for the lstchain code.

**Comment by kosack** [comment]
Right now, all the camera definitions are "SimTel" ones. Why rename only LST?  The camera definitions in ctapipe-extra are just for testing, anyhow,  and are linked to the MC prod, not for real data. You could simply include the "correct" definition in the LST event source package, and then you have full control. I don't really like that the lst event source depends on ctapipe-extra (which may disappear at some point).

**Comment by maxnoe** [comment]
> You could simply include the "correct" definition in the LST event source package, and then you have full control. I don't really like that the lst event source depends on ctapipe-extra (which may disappear at some point).

That's already the case

**Comment by maxnoe** [comment]
I'll close this

**Pull request closed without merging**
