### PR TITLE
Atmosphere calibration

### PR DESCRIPTION
**Pull request by bregeon**
Hello,
I would like to have these few files available here to facilitate the atmosphere calibration pipeline.
Files are quite small but the "radiosonde" one that is 10 MB.
Cheers
Johan

### CODE REVIEW

**Comment by bregeon** [comment]
and if you wonder, the code to read and plot these data are in development here:
https://github.com/bregeon/ctapipe/tree/atmo-dev/ctapipe/atmosphere
and clearly not quite in the state of being merged.

**Comment by kosack** [comment]
Ok, I'll merge this now and create a new package (ctapipe will then need an update so this version is used)

**Comment by kosack** [comment]
By the way, if these are ECSV files (as they appear to be), I think I will rename them ".ecsv.txt", so that the `ctapipe.utils.get_table_dataset()` function finds them automatically.

**Comment by kosack** [comment]
Actually, I've reverted this PR - the files are not in the current format readnable by `astropy.table.Table.read()`.  At least, it was not able to guess the format.  Could you make them compliant?

**Comment by kosack** [comment]
(and then re-do the PR)

**Pull request merged**
