### PR TITLE
Add prod3 file with lsts containing calibration events and true mc photons

### PR DESCRIPTION
**Pull request by maxnoe**
This is a file I simulated (latest simtel release but prod3 config) containing 4 LSTs with

* 2 dark pedestal events
* 2 open shutter pedestal events
* 2 internal led events
* 2 external laser events
* 2 500 GeV gammas including the true photo electron image

This is needed for being able to test trigger types with the simtel event source

### CODE REVIEW

**Comment by kosack** [comment]
Perhaps just replace calib_events.simtel.gz with this? Or remove that one?

**Comment by maxnoe** [comment]
That would break tests in ctapipe until we make ctapipe use the new version. Should we do that?

**Comment by maxnoe** [comment]
Removed

**Comment by maxnoe** [comment]
closed in favor of #31 as taht file has diffuse gammas

**Pull request closed without merging**
