### PR TITLE
Python package

### PR DESCRIPTION
**Pull request by maxnoe**
Make the extra repository a pip installable python package.

This should make it possible to get rid of the need to set `CTAPIPE_EXTRA_DIR` for everything and provides a version that ctapipe can require. 

This also should be able to get rid of the submodule over at ctapipe, which tends to confuse even advanced git users.

### CODE REVIEW

**Comment by jacquemier** [comment]
Not sure to understand.
You  add **init**.py and setup.py to make it pip installable. Is it correct ?
Why do you change from datasets to  ctapipe_resources.
Will it still be a ctapipe-submodule after that ?

**Comment by maxnoe** [comment]
> You add init.py and setup.py to make it pip installable. Is it correct ?

Yes. Side effect is that the resources have a version now.

> Why do you change from datasets to ctapipe_resources.

Just so the directory has the the name of the python package. If we want to keep the `datasets` name, i would move it to a subdirectory `ctapipe_resources/datasets`.

> Will it still be a ctapipe-submodule after that 

Should not be necessary anymore, which is kind of the point of this PR.

I'd like to mention another proposal by @mackaiver:
Just move it to a resources directory over at ctapipe. This has also its advantages. I would even prefer that I guess.

This PR is a suggestion if we want to keep it in different repositories. But I don't really know a reason to do that.

**Comment by kosack** [comment]
Ok, so if I understand correctly it is now a separate package and we could remove the submodule, and make the new package an install dependency. Correct?

Since we are using conda for package management, it would be nice to have it also build-able as a conda package. For that you just need a conda recipe file as well as setup.py, which I think can be generated automatically with `conda skeleton pypi`, or probably just hand-creating it, since it's not very complicated.  Could you add that?

**Comment by maxnoe** [comment]
I could do that. But I would favor the solution to just move the data to a resources directory in the ctapipe repository.

I think we should discuss this option first before we continue to add stuff here.

**Comment by kosack** [comment]
The reason for the separation was that the data files are really something separate from the code, will likely change or go away, and may have a large file size compared with the rest of the code (the extras repo could grow very large if we start updating the binaries). 

This method of having an "extras" package is a common idiom to separate the data.  Really, I wouldn't mind just having a rsync-able repo somewhere and have all tests fetch files as they need them, but the git repo method seemed easiest (even if git is not really good with binary files).  The user only needs the latest version of the files, not the full git history, however, so git is not really idea for this.  In any case, it needs a lot of cleaning up - most of the files in `datasets` are not used or in formats that are not supported officially.

**Comment by kosack** [comment]
I think having it in a git repo, but that the user never needs to download (because it is a package we build and provide) is the best solution, and is basically what you are doing now.  They would only git-install the `ctapipe` code for development, and just fetch the correct version of the `ctapipe_resources` package via conda.

**Comment by maxnoe** [comment]
I see. Having a lot of binaries that will propably never end up in production will just bloat the history.

**Pull request merged**
