### PR TITLE
fix NectarCam geometry orientation

### PR DESCRIPTION
**Pull request by sizun**
See [nectarchain/#4](https://github.com/cta-observatory/nectarchain/issues/4) and [ctapipe/#1085](https://github.com/cta-observatory/ctapipe/pull/1085).

### CODE REVIEW

**Comment by kosack** [comment]
Should this replace the old one? Or do you want to keep the incorrect one around?  I'm going to clean up this data soon (and remove ctapipe-extra completely in favor of a download-based data store, so knowing what files are still valid will be useful).

**Comment by sizun** [comment]
> Should this replace the old one? Or do you want to keep the incorrect one around?

At least _NectarCam.camgeom.fits.gz_ (right orientation, wrong pixel numbering) should be removed. Maybe _NectarCam-002.camgeom.fits.gz_ (wrong orientation, right numbering) can be kept for a little while? I do not know.
By the way, the LSTCam-002 geometry suffers from the same orientation problem.

**Comment by sizun** [comment]
Hi @kosack , do you need more info before merging this PR?

**Comment by maxnoe** [comment]
I think @kosack thought you will want to implement the changes you mentioned (remove the old files?)

**Comment by sizun** [comment]
If I remove the old geometries, is it OK if there is no longer any file named _NectarCam.camgeom.fitz.fz_ or should I make it a copy of the new geometry _NectarCam-003.camgeom.fitz.fz_ ?

**Comment by kosack** [comment]
You can just remove the old ones, these files are only used for testing. If you load a simulation, new ones are generated in-memory, so you can just replace the original NectarCam.camgeom.fits file (unless you really need to be able to load up old versions)

**Pull request merged**
