### PR TITLE
MAGIC camera geometry

### PR DESCRIPTION
**Pull request by labsaha**
This PR is to add MAGIC camera geometry to ctapipe

### CODE REVIEW

**Comment by maxnoe** [comment]
Why is it called `I`? It's the MAGIC II camera geometry, right? Not the old camera with the two different kinds of pmts.

**Comment by labsaha** [comment]
@MaxNoe Yes, it is MAGIC II camera geometry. I can change the name to just 'MAGIC', otherwise it will be confusing. The coordinates  in MAGIC frame of reference is also given here (<https://github.com/cta-observatory/cta-lstchain/blob/master/magic-lst/magic_camera_info.txt>). You can check this if these are the correct coordinates you were talking about.

**Comment by maxnoe** [comment]
You can find the MARS and python code I used here: https://github.com/tudo-astroparticlephysics/mgeomcam_to_ctapipe

Maybe we should just use that? As it is reproducible and can extract all possible geometries from MARS?

**Comment by maxnoe** [comment]
I also implemented the camera rotation there

**Comment by labsaha** [comment]
@MaxNoe Could you commit the script to the cta-lstchain? It would be good to have the scripts/notebooks etc in a place like that where we are working on something related to MAGIC. Anyway, in the end, these geometry files are perhaps not permanent solutions for importing camera geometry in ctapipe. As Karl said it should read the info from the header of the data file if they are available.

**Comment by maxnoe** [comment]
I don't think we should save the CameraGeometry with each and every data file, it's something that changes rarely, if at all.

**Comment by maxnoe** [comment]
> Could you commit the script to the cta-lstchain? It would be good to have the scripts/notebooks etc in a place like that where we are working on something related to MAGIC

You could fork it into cta-observatory.

**Review by kosack — APPROVED** [review]

**Pull request merged**
