### PR TITLE
Add new LST camera geometry (version 3) with correct camera rotation.

### PR DESCRIPTION
**Pull request by FrancaCassol**
LST geometry version 2 corresponds to the Engineering Camera Frame not to the Camera Frame. This PR adds LSTCam-003.camgeom.fits.gz where the two frames should be correct. Here a plot of the two geometries where the pixels 0, 2, 7 and 1854 are highlighted in red

 
LST_geometry_002
LST_geometry_003

### CODE REVIEW

**Comment by FrancaCassol** [comment]
Hi @MaxNoe, 
is this geometry correct? 
If yes, could this PR be accepted?
Thanks

**Comment by kosack** [comment]
looks correct to me.

**Comment by maxnoe** [comment]
@FrancaCassol there is a nice way to make sure this is correct and the camera coordinates work.

Do you have pedestal data with stars in the field of view (e.g. Crab with Ceta Tauri)?

**Comment by FrancaCassol** [comment]
Hi @MaxNoe,
unfortunately not so evident for the moment. But I will keep it in mind and come to you as soon as I get them.

**Comment by maxnoe** [comment]
See https://github.com/cta-observatory/ctapipe/pull/1085 and https://github.com/watsonjj/CHECLabPySB/blob/master/CHECLabPySB/d190607_pointing/engineeringv2.ipynb for what I had in mind

**Pull request merged**
